### ISSUE TITLE
Stuck on boot

### ISSUE THREAD

**Issue by ps3vd0** [daimaou92/install-arch-vmwarefusion-techpreview#1]
Hi daimaou, I'm trying to get arch installed on my M1 using VMWare Fusion Tech Preview and I tried going through the steps but I'm coming to a road-block. 

After modifying the VM settings just as you recommend on your steps and launching it (step 3), I'm greeted by the GNU Grub with the multiple options.

Once I hit “Archboot Arch Linux AA64” I get stuck on the below:

```
Running menu entry:
Archboot Arch Linux AA64 …
Please wait …
EFI stub: Booting Linux Kernel…
EFI stub: Using DTB from configuration table
EFI stub: Loaded ignited from LINUX_EFI_INITDR_MEDIA_GUID device path
EFI stub: Exiting boot services…
```

I would love to get this working and enjoy a similar experience with Arch as you do.
---

I tried looking for another way to contact you but couldnt find the twitter account so if this is not the best way please feel free to remove the issue.

**Comment by ps3vd0** [comment]
This is the ISO I downloaded: https://pkgbuild.com/~tpowa/archboot/iso/aarch64/latest/archboot-2023.02.01-21.50-aarch64.iso

**Comment by ps3vd0** [comment]
I think I got it resolved for now. I was using VMWare Fusion Tech Preview. Downloaded VMWare Fusion 13 Player and it booted up.

I'll continue the steps.

Apologies for the false alarm. Feel free to delete the issue.

**Comment by daimaou92** [comment]
So sorry for the late response. Haven't been monitoring this in a while.
Great that you were able to get it fixed. Enjoy.
