### ISSUE TITLE
ISO file is not available anymore!

### ISSUE THREAD

**Issue by meanii** [daimaou92/install-arch-vmwarefusion-techpreview#2]
[Arch ISO for Silicon](https://pkgbuild.com/~tpowa/archboot/iso/aarch64/latest/archboot-2023.01.22-21.50-aarch64.iso) is not seems to available anymore.
can you provide any other ISO image?

**Comment by daimaou92** [comment]
Hey @meanii - didn't realize the url gets deprecated like that. I would encourage you to look at: https://archboot.com/iso/aarch64/latest/.
However, I have done a recent test but am unable to boot using the ISOs from there for some reason. Don't have the time to debug this at this time.
Keeping this open for now.

**Comment by daimaou92** [comment]
I've added a ISO I could find on the internet that I've tested with these scripts to work on VMWare Fusion Tech Preview 2023. Find it in the [latest release](https://github.com/daimaou92/install-arch-vmwarefusion-techpreview/releases/tag/v0.1.0).
